version : "3"
services:
  db:
    platform: linux/x86_64
    container_name: football_db
    image: mysql
    environment:
      MYSQL_DATABASE: football_db
      MYSQL_USER: football
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - ./db/data:/var/lib/mysql:rw
    ports:
      - "3306:3306"
    restart: always

  redis-cluster:
    container_name: redis-master-1
    image: redis:latest
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis/master1.conf:/usr/local/etc/redis/redis.conf
    restart: always
    ports:
      - "7001:7001"
      - "7002:7002"
      - "7003:7003"
      - "7004:7004"
      - "7005:7005"
      - "7006:7006"

  redis-master-2:
    network_mode: "service:redis-cluster"
    container_name: redis-master-2
    image: redis:latest
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis/master2.conf:/usr/local/etc/redis/redis.conf
    restart: always

  redis-master-3:
    network_mode: "service:redis-cluster"
    container_name: redis-master-3
    image: redis:latest
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis/master3.conf:/usr/local/etc/redis/redis.conf
    restart: always

  redis-slave-1:
    network_mode: "service:redis-cluster"
    container_name: redis-slave-1
    image: redis:latest
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis/slave1.conf:/usr/local/etc/redis/redis.conf
    restart: always

  redis-slave-2:
    network_mode: "service:redis-cluster"
    container_name: redis-slave-2
    image: redis:latest
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis/slave2.conf:/usr/local/etc/redis/redis.conf
    restart: always

  redis-slave-3:
    network_mode: "service:redis-cluster"
    container_name: redis-slave-3
    image: redis:latest
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis/slave3.conf:/usr/local/etc/redis/redis.conf
    restart: always

  redis-cluster-entry:
    network_mode: "service:redis-cluster"
    platform: linux/x86_64
    image: redis:latest
    container_name: football-redis-cluster-entry
    command: redis-cli --cluster create 127.0.0.1:7001 127.0.0.1:7002 127.0.0.1:7003 --cluster-yes
    depends_on:
      - redis-cluster
      - redis-master-2
      - redis-master-3

  redis-cluster-replicas-1:
    network_mode: "service:redis-cluster"
    platform: linux/x86_64
    image: redis:latest
    container_name: football-redis-cluster-replicas-1
    command: redis-cli --cluster add-node 127.0.0.1:7004 127.0.0.1:7001 --cluster-slave
    depends_on:
      - redis-slave-1

  redis-cluster-replicas-2:
    network_mode: "service:redis-cluster"
    platform: linux/x86_64
    image: redis:latest
    container_name: football-redis-cluster-replicas-2
    command: redis-cli --cluster add-node 127.0.0.1:7005 127.0.0.1:7002 --cluster-slave
    depends_on:
      - redis-slave-2

  redis-cluster-replicas-3:
    network_mode: "service:redis-cluster"
    platform: linux/x86_64
    image: redis:latest
    container_name: football-redis-cluster-replicas-3
    command: redis-cli --cluster add-node 127.0.0.1:7006 127.0.0.1:7003 --cluster-slave
    depends_on:
      - redis-slave-3
