spring:
  profiles:
    group:
      - "local" : "local, common"
      - "dev" : "dev, common"
      - "prod" : "prod, common"

---

spring:
  profile: common

jwt:
  header: Authorization
  secret: bWUtaHllb25pYy1teS1wbGktbWUtaHllb25pYy1teS1wbGktbWUtaHllb25pYy1teS1wbGktbWUtaHllb25pYy1teS1wbGk=
  token-validity-in-seconds: 1800

---

spring:
  profile: local

server:
  port: 8000

---

spring:
  profile: dev

server:
  port: 8010
