server:
  port: 8000
  host:
    api:
    websocket:

jwt:
  header: Authorization
  secret: bWUtaHllb25pYy1teS1wbGktbWUtaHllb25pYy1teS1wbGktbWUtaHllb25pYy1teS1wbGktbWUtaHllb25pYy1teS1wbGk=
  token-validity-in-seconds: 1800