server:
  port: 8000
  host:
    api: football-lb-app-1899246839.ap-northeast-2.elb.amazonaws.com
    websocket:
      public: 3.39.254.213:8000
      private: 10.0.11.55:8000

jwt:
  header: Authorization
  secret: bWUtaHllb25pYy1teS1wbGktbWUtaHllb25pYy1teS1wbGktbWUtaHllb25pYy1teS1wbGktbWUtaHllb25pYy1teS1wbGk=
  token-validity-in-seconds: 1800