server:
  port: 9000
  host:
    api: localhost:9090
    websocket:
      public: localhost:9000
      private: localhost:9000

jwt:
  header: Authorization
  secret: bWUtaHllb25pYy1teS1wbGktbWUtaHllb25pYy1teS1wbGktbWUtaHllb25pYy1teS1wbGktbWUtaHllb25pYy1teS1wbGk=
  token-validity-in-seconds: 1800