server:
  port: 8080
  host:
    api:
    websocket:

spring:
  profiles: prod

  datasource:
    url: jdbc:mysql://football-db-mysql.ckt0scabogid.ap-northeast-2.rds.amazonaws.com:3306/football_db_mysql
    username: admin
    password: 1q2w3e4r!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: Mysql
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: none

    flyway:
      enabled: true
      baseline-on-migrate: true

  redis:
    host: football-redis.qyvl4a.clustercfg.apn2.cache.amazonaws.com:6379
    port: 6379

jwt:
  header: Authorization
  secret: bWUtaHllb25pYy1teS1wbGktbWUtaHllb25pYy1teS1wbGktbWUtaHllb25pYy1teS1wbGktbWUtaHllb25pYy1teS1wbGk=
  token-validity-in-seconds: 1800