server:
  port: 9090
  host:
    api: localhost:9090
    chatting:
      public: localhost:9000
      private: localhost:9000
spring:
  profiles: local

  datasource:
    url: jdbc:mysql://localhost:3306/football_db?characterEncoding=UTF-8
    username: football
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: Mysql
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: none

  flyway:
    enabled: true
    baseline-on-migrate: true

  redis:
    host: localhost
    port: 7001

    # local 환경에서 redis cluster 활용시 사용하는 변수
    cluster:
      nodes:
        - 127.0.0.1:7001
        - 127.0.0.1:7002
        - 127.0.0.1:7003
        - 127.0.0.1:7004
        - 127.0.0.1:7005
        - 127.0.0.1:7006

jwt:
  header: Authorization
  secret: bWUtaHllb25pYy1teS1wbGktbWUtaHllb25pYy1teS1wbGktbWUtaHllb25pYy1teS1wbGktbWUtaHllb25pYy1teS1wbGk=
  token-validity-in-seconds: 1800