name: Java CD with Gradle

on:
   workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      # 디렉토리 생성
      - name: Make Directory
        run: mkdir -p football

      # Api 서버 Jar 파일 복사
      - name: Copy Jar
        run: cp ./football-api-server/build/libs/*.jar ./football

      # Websocket Jar 파일 복사
      - name: Copy Jar
        run: cp ./football-websocket-server/build/libs/*.jar ./football

#    - uses: actions/checkout@v2
#    - name: Run scripts in server
#      uses: appleboy/ssh-action@master
#      with:
#        key: ${{ secrets.SSH_KEY }}
#        host: ${{ secrets.HOST }}
#        username: ${{ secrets.USER }}
#        script: # EC2 서버 접속 후 사용할 커맨드